<?php

require '../vendor/autoload.php'; // Asegúrate de que la ruta a vendor es correcta

use PhpOffice\PhpWord\TemplateProcessor;

// Verifica que los datos del formulario se han enviado
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Obtén los datos del formulario
        $data = [
            'nombre' => $_POST['nombre'] ?? '',
            'primerA' => $_POST['primerA'] ?? '',
            'segundoA' => $_POST['segundoA'] ?? '',
            'Nombre_Completo' => $_POST['Nombre_Completo'] ?? '',
            'nss' => $_POST['nss'] ?? '',
            'curp' => $_POST['curp'] ?? '',
            'ine' => $_POST['ine'] ?? '',
            'rfc' => $_POST['rfc'] ?? '',
            'sexo' => $_POST['sexo'] ?? '',
            'escolaridad' => $_POST['escolaridad'] ?? '',
            'lugarnacimiento' => $_POST['lugarnacimiento'] ?? '',
            'fechanacimiento' => $_POST['fechanacimiento'] ?? '',
            'edad' => $_POST['edad'] ?? '',
            'estadocivil' => $_POST['estadocivil'] ?? '',
            'domicilio' => $_POST['domicilio'] ?? '',
            'colonia' => $_POST['colonia'] ?? '',
            'municipio' => $_POST['municipio'] ?? '',
            'cp' => $_POST['cp'] ?? '',
            'estado' => $_POST['estado'] ?? '',
            'telefono' => $_POST['telefono'] ?? '',
            'sueldo' => $_POST['sueldo'] ?? '',
            'mail' => $_POST['mail'] ?? '',
            'beneficiario' => $_POST['beneficiario'] ?? '',
            'fotografia' => $_POST['fotografia'] ?? '',
            'nombrepadre' => $_POST['nombrepadre'] ?? '',
            'ocupacionpadre' => $_POST['ocupacionpadre'] ?? '',
            'telefonopadre' => $_POST['telefonopadre'] ?? '',
            'nombremadre' => $_POST['nombremadre'] ?? '',
            'ocupacionmadre' => $_POST['ocupacionmadre'] ?? '',
            'telefonomadre' => $_POST['telefonomadre'] ?? '',
            'hijoa' => $_POST['hijoa'] ?? '',
            'hijob' => $_POST['hijob'] ?? '',
            'nombreesposa' => $_POST['nombreesposa'] ?? '',
            'dia_registro' => $_POST['dia_registro'] ?? '',
            'mes_registro' => $_POST['mes_registro'] ?? '',
            'primaria' => $_POST['primaria'] ?? '',
            'entidad_federativa_primaria' => $_POST['entidad_federativa_primaria'] ?? '',
            'anos_cursados_primaria' => $_POST['anos_cursados_primaria'] ?? '',
            'documento_recibido_primaria' => $_POST['documento_recibido_primaria'] ?? '',
            'secundaria' => $_POST['secundaria'] ?? '',
            'entidad_federativa_secundaria' => $_POST['entidad_federativa_secundaria'] ?? '',
            'anos_cursados_secundaria' => $_POST['anos_cursados_secundaria'] ?? '',
            'documento_recibido_secundaria' => $_POST['documento_recibido_secundaria'] ?? '',
            'bachillerato' => $_POST['bachillerato'] ?? '',
            'entidad_federativa_bachillerato' => $_POST['entidad_federativa_bachillerato'] ?? '',
            'anos_cursados_bachillerato' => $_POST['anos_cursados_bachillerato'] ?? '',
            'documento_recibido_bachillerato' => $_POST['documento_recibido_bachillerato'] ?? '',
            'deportes' => $_POST['deportes'] ?? '',
            'cual1' => $_POST['cual1'] ?? '',
            'lo_practica1' => $_POST['lo_practica1'] ?? '',
            'manuales' => $_POST['manuales'] ?? '',
            'cual2' => $_POST['cual2'] ?? '',
            'lo_practica2' => $_POST['lo_practica2'] ?? '',
            'fisicas' => $_POST['fisicas'] ?? '',
            'cual3' => $_POST['cual3'] ?? '',
            'lo_practica3' => $_POST['lo_practica3'] ?? '',
            'culturales' => $_POST['culturales'] ?? '',
            'cual4' => $_POST['cual4'] ?? '',
            'lo_practica4' => $_POST['lo_practica4'] ?? '',
            'otros' => $_POST['otros'] ?? '',
            'cual5' => $_POST['cual5'] ?? '',
            'lo_practica5' => $_POST['lo_practica5'] ?? '',
            'cuales_son' => $_POST['cuales_son'] ?? '',
            'cual6' => $_POST['cual6'] ?? '',
            'lo_practica6' => $_POST['lo_practica6'] ?? '',
            'urbana' => $_POST['urbana'] ?? '',
            'media' => $_POST['media'] ?? '',
            'popular' => $_POST['popular'] ?? '',
            'periferica' => $_POST['periferica'] ?? '',
            'barriada' => $_POST['barriada'] ?? '',
            'suburbio' => $_POST['suburbio'] ?? '',
            'campestre' => $_POST['campestre'] ?? '',
            'ejidal' => $_POST['ejidal'] ?? '',
            'centrica' => $_POST['centrica'] ?? '',
            'lujo' => $_POST['lujo'] ?? '',
            'casa_sola' => $_POST['casa_sola'] ?? '',
            'casa_en_condominio' => $_POST['casa_en_condominio'] ?? '',
            'departamento' => $_POST['departamento'] ?? '',
            'unidad_habitacional' => $_POST['unidad_habitacional'] ?? '',
            'vivienda_popular' => $_POST['vivienda_popular'] ?? '',
            'interes_social' => $_POST['interes_social'] ?? '',
            'interes_medio' => $_POST['interes_medio'] ?? '',
            'residencial' => $_POST['residencial'] ?? '',
            'vecindad' => $_POST['vecindad'] ?? '',
            'choza_o_jacal' => $_POST['choza_o_jacal'] ?? '',
            'propia' => $_POST['propia'] ?? '',
            'pagandola' => $_POST['pagandola'] ?? '',
            'de_familiares' => $_POST['de_familiares'] ?? '',
            'de_amigos' => $_POST['de_amigos'] ?? '',
            'alquiler' => $_POST['alquiler'] ?? '',
            'en_comodato' => $_POST['en_comodato'] ?? '',
            'con_credito' => $_POST['con_credito'] ?? '',
            'hipotecario' => $_POST['hipotecario'] ?? '',
            'infonavit' => $_POST['infonavit'] ?? '',
            'fovissste' => $_POST['fovissste'] ?? '',
            'una_recamara' => $_POST['una_recamara'] ?? '',
            'dos_recamaras' => $_POST['dos_recamaras'] ?? '',
            'tres_recamaras' => $_POST['tres_recamaras'] ?? '',
            'mas_de_tres_recamaras' => $_POST['mas_de_tres_recamaras'] ?? '',
            'sala' => $_POST['sala'] ?? '',
            'comedor' => $_POST['comedor'] ?? '',
            'cocina' => $_POST['cocina'] ?? '',
            'un_baño' => $_POST['un_baño'] ?? '',
            'un_y_medio_baño' => $_POST['un_y_medio_baño'] ?? '',
            'dos_baños' => $_POST['dos_baños'] ?? '',
            'mas_de_dos_baños' => $_POST['mas_de_dos_baños'] ?? '',
            'jardin' => $_POST['jardin'] ?? '',
            'estancia_o_cuarto_de_tv' => $_POST['estancia_cuarto_tv'] ?? '',
            'biblioteca' => $_POST['biblioteca'] ?? '',
            'sala_o_salon_de_juegos' => $_POST['sala_o_salon_de_juegos'] ?? '',
            'estudio' => $_POST['estudio'] ?? '',
            'garage' => $_POST['garage'] ?? '',
            'cuarto_de_servicio' => $_POST['cuarto_de_servicio'] ?? '',
            'un_piso' => $_POST['un_piso'] ?? '',
            'dos_pisos' => $_POST['dos_pisos'] ?? '',
            'mas_de_dos_pisos' => $_POST['mas_de_dos_pisos'] ?? '',
            'patio' => $_POST['patio'] ?? '',
            'credito_hipotecario' => $_POST['credito_hipotecario'] ?? '',
            'credito_personal' => $_POST['credito_personal'] ?? '',
            'credito_refaccionario' => $_POST['credito_refaccionario'] ?? '',
            'credito_de_avio' => $_POST['credito_de_avio'] ?? '',
            'credito_autromotiz' => $_POST['credito_autromotiz'] ?? '',
            'credito_comercial' => $_POST['credito_comercial'] ?? '',
            'credito_mercantil' => $_POST['credito_mercantil'] ?? '',
            'credito_departamental' => $_POST['credito_departamental'] ?? '',
            'credito_bancario' => $_POST['credito_bancario'] ?? '',
            'tarjetas_de_credito' => $_POST['tarjetas_de_credito'] ?? '',
            'otros_creditos' => $_POST['otros_creditos'] ?? '',
            'adeudo_infonavit' => $_POST['adeudo_infonavit'] ?? '',
            'adeudo_fonacot' => $_POST['adeudo_fonacot'] ?? '',
            'adeudo_fovissste' => $_POST['adeudo_fovissste'] ?? '',
            'adeudos_bancarios' => $_POST['adeudos_bancarios'] ?? '',
            'adeudos_hipotecarios' => $_POST['adeudos_hipotecarios'] ?? '',
            'adeudos_automotrises' => $_POST['adeudos_automotrises'] ?? '',
            'adeudos_mercantiles' => $_POST['adeudos_mercantiles'] ?? '',
            'adeudos_departamentales' => $_POST['adeudos_departamentales'] ?? '',
            'adeudos__comerciales' => $_POST['adeudos_comerciales'] ?? '',
            'radio' => $_POST['radio'] ?? '',
            'televisor' => $_POST['televisor'] ?? '',
            'equipo_de_sonido' => $_POST['equipo_de_sonido'] ?? '',
            'home_teather' => $_POST['home_teather'] ?? '',
            'dvd' => $_POST['dvd'] ?? '',
            'video_cassetera_vhs' => $_POST['video_cassetera_vhs'] ?? '',
            'equipo_de_videojuegos' => $_POST['equipo_de_videojuegos'] ?? '',
            'computadora' => $_POST['computadora'] ?? '',
            'impresora' => $_POST['impresora'] ?? '',
            'equipo_de_fax' => $_POST['equipo_de_fax'] ?? '',
            'estufa' => $_POST['estufa'] ?? '',
            'refrigerador' => $_POST['refrigerador'] ?? '',
            'lavadora' => $_POST['lavadora'] ?? '',
            'secadora' => $_POST['secadora'] ?? '',
            'licuadora' => $_POST['licuadora'] ?? '',
            'horno_de_microondas' => $_POST['horno_de_microondas'] ?? '',
            'lavavajillas' => $_POST['lavavajillas'] ?? '',
            'freidora' => $_POST['freidora'] ?? '',
            'tostador_waflerasandwichera' => $_POST['tostador_waflerasandwichera'] ?? '',
            'extractoe_de_jugos' => $_POST['extractoe_de_jugos'] ?? '',
            'agua_potable' => $_POST['agua_potable'] ?? '',
            'agua_de_poso' => $_POST['agua_de_poso'] ?? '',
            'suministro_po_pipa' => $_POST['suministro_po_pipa'] ?? '',
            'agua_de_lluvia' => $_POST['agua_de_lluvia'] ?? '',
            'agua_de_garrafon' => $_POST['agua_de_garrafon'] ?? '',
            'drenaje_publico' => $_POST['drenaje_publico'] ?? '',
            'fosa_septica' => $_POST['fosa_septica'] ?? '',
            'alumbrado_publico' => $_POST['alumbrado_publico'] ?? '',
            'banquetas' => $_POST['banquetas'] ?? '',
            'asfalto' => $_POST['asfalto'] ?? '',
            'pavimento' => $_POST['pavimento'] ?? '',
            'terraceria' => $_POST['terraceria'] ?? '',
            'parque' => $_POST['parque'] ?? '',
            'mercados_publicos' => $_POST['mercados_publicos'] ?? '',
            'sistema_de_vigilancia' => $_POST['sistema_de_vigilancia'] ?? '',
            'servicio_postal' => $_POST['servicio_postal'] ?? '',
            'hospitales' => $_POST['hospitales'] ?? '',
            'centros_medicos' => $_POST['centros_medicos'] ?? '',
            'centros_culturales' => $_POST['centros_culturales'] ?? '',
            'panaderias' => $_POST['panaderias'] ?? '',
            'energia_electrica' => $_POST['energia_electrica'] ?? '',
            'servicio_telefonico' => $_POST['servicio_telefonico'] ?? '',
            'television_por_cable' => $_POST['television_por_cable'] ?? '',
            'recoleccion_de_basura' => $_POST['recoleccion_de_basura'] ?? '',
            'seguridad_privada' => $_POST['seguridad_privada'] ?? '',
            'seguridad_publica' => $_POST['seguridad_publica'] ?? '',
            'acceso_controlado' => $_POST['acceso_controlado'] ?? '',
            'transporte_publico' => $_POST['transporte_publico'] ?? '',
            'telefono_publico' => $_POST['telefono_publico'] ?? '',
            'centros_comerciales' => $_POST['centros_comerciales'] ?? '',
            'escuelas_publicas' => $_POST['escuelas_publicas'] ?? '',
            'instalaciones_deportivas' => $_POST['instalaciones_deportivas'] ?? '',
            'jardines' => $_POST['jardines'] ?? '',
            'vigilancia_nocturna' => $_POST['vigilancia_nocturna'] ?? '',
            'lecherias_publicas' => $_POST['lecherias_publicas'] ?? '',
            'tiendas_rurales' => $_POST['tiendas_rurales'] ?? '',
            'iglesias' => $_POST['iglesias'] ?? '',
            'bancos' => $_POST['bancos'] ?? '',
            'suministros_de_gas' => $_POST['suministros_de_gas'] ?? '',
            'gastos_mensuales' => $_POST['gastos_mensuales'] ?? '',
            'pago_hipotecario' => $_POST['pago_hipotecario'] ?? '',
            'pago_de_infonavit' => $_POST['pago_de_infonavit'] ?? '',
            'pago_de_fovissste' => $_POST['pago_de_fovissste'] ?? '',
            'pago_de_renta' => $_POST['pago_de_renta'] ?? '',
            'pago_de_luz' => $_POST['pago_de_luz'] ?? '',
            'pago_de_agua' => $_POST['pago_de_agua'] ?? '',
            'pago_de_predial' => $_POST['pago_de_predial'] ?? '',
            'pago_de_gas' => $_POST['pago_de_gas'] ?? '',
            'pago_de_telefono' => $_POST['pago_de_telefono'] ?? '',
            'pago_de_transporte' => $_POST['pago_de_transporte'] ?? '',
            'pago_de_alimentos' => $_POST['pago_de_alimentos'] ?? '',
            'pagos_medicos' => $_POST['pagos_medicos'] ?? '',
            'mantenimiento_de_vivienda' => $_POST['mantenimiento_de_vivienda'] ?? '',
            'servicio_de_tv' => $_POST['servicio_de_tv'] ?? '',
            'gastos_vacacionales' => $_POST['gastos_vacacionales'] ?? '',
            'haorro' => $_POST['haorro'] ?? '',
            'educacion' => $_POST['educacion'] ?? '',
            'utiles_escolares' => $_POST['utiles_escolares'] ?? '',
            'uniformes_escolares' => $_POST['uniformes_escolares'] ?? '',
            'transporte_escolar' => $_POST['transporte_escolar'] ?? '',
            'cuotas_escolares' => $_POST['cuotas_escolares'] ?? '',
            'servicio_medico' => $_POST['servicio_medico'] ?? '',
            'calzado_vestido' => $_POST['calzado_vestido'] ?? '',
            'articulos_de_consumo' => $_POST['articulos_de_consumo'] ?? '',
            'articulos_de_aseo' => $_POST['articulos_de_aseo'] ?? '',
            'articulos_de_uso_personal' => $_POST['articulos_de_uso_personal'] ?? '',
            'mantenimiento_de_vehiculos' => $_POST['mantenimiento_de_vehiculos'] ?? '',
            'servicio_domestico' => $_POST['servicio_domestico'] ?? '',
            'cuotas_de_clubes' => $_POST['cuotas_de_clubes'] ?? '',
            'total_adeudos_gastos_mensuales' => $_POST['total_adeudos_gastos_mensuales'] ?? '',
        ];
     
    // Campos de gastos mensuales
    $gastosMensuales = [
        'pago_hipotecario',
        'pago_de_infonavit',
        'pago_de_fovissste',
        'pago_de_renta',
        'pago_de_luz',
        'pago_de_agua',
        'pago_de_predial',
        'pago_de_gas',
        'pago_de_telefono',
        'pago_de_transporte',
        'pago_de_alimentos',
        'pagos_medicos',
        'mantenimiento_de_vivienda',
        'servicio_de_tv',
        'gastos_vacacionales',
        'haorro',
        'educacion',
        'utiles_escolares',
        'uniformes_escolares',
        'transporte_escolar',
        'cuotas_escolares',
        'servicio_medico',
        'calzado_vestido',
        'articulos_de_consumo',
        'articulos_de_aseo',
        'articulos_de_uso_personal',
        'mantenimiento_de_vehiculos',
        'servicio_domestico',
        'cuotas_de_clubes',
        'total_adeudos_gastos_mensuales',
    ];
    


    // Reemplaza campos vacíos por 'NO' o '$0' según corresponda
    foreach ($data as $key => $value) {
        if (empty($value)) {
            if (in_array($key, $gastosMensuales)) {
                $data[$key] = '$0';
            } else {
                $data[$key] = 'NO';
            }
        }
    }

    // Carga el archivo de plantilla
    $templateProcessor = new TemplateProcessor('..//contrato_template.docx'); // Asegúrate de que la ruta es correcta

    // Reemplaza los campos en el documento
    foreach ($data as $key => $value) {
        $templateProcessor->setValue($key, $value);
    }

    // Guarda el archivo actualizado
    $outputFile = '../documento_actualizado.docx';
    $templateProcessor->saveAs($outputFile);

    

    // Forzar la descarga del archivo
    header('Content-Description: File Transfer');
    header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    header('Content-Disposition: attachment; filename="' . basename($outputFile) . '"');
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    header('Content-Length: ' . filesize($outputFile));
    flush(); // Flush system output buffer
    readfile($outputFile);

    // Elimina el archivo temporal
    unlink($outputFile);
    exit;
}
?>
